### ISSUE TITLE
unknown words should report an error

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-editor#26]
![image](https://github.com/presciencelabs/tabitha-editor/assets/4412848/713773e6-619b-477a-bb10-f8c4f2cd3d81)

**Comment by craigp-atw** [comment]
The last step for this is writing lookup rules for all the phrasal verbs such as 'cut off', 'grow up', etc. Then the 'off', 'up', etc. will not flag as unknown words.

**Comment by craigp-atw** [comment]
Upon further reflection, I don't think this should ever be an error. It's better as a warning (which it is now), as there are delays in adding words to the ontology, and some words don't have all their forms recognized. I think we can close this issue.

The main part of this issue was accurately identifying unknown words, which the editor has now accomplished.
